from recipes import base  # Generated by recipe-press

recipe = base.Recipe(
    {
        'title': 'YetAnotherRecipe',
        'steps': [{"message": "Here's the first step. Do it.", "next": 1, "options": [{"text": "Okay", "next": 1}, {"text": "Nah", "next": 2}]}, {"message": "Put the stuff in the thing.", "options": [{"text": "Onward!", "next": 2}], "next": 2}, {"message": "Heat up to temp", "parameters": {"temp": 50}, "baseTask": "cool", "next": 3}, {"message": "Stir Stir!", "parameters": {"time": 30}, "baseTask": "stir", "next": 4, "done": True}, {"message": "Bask in your own glory", "done": True}]
    }
)
