name: Backend Tests
on:
  pull_request:
    branches:
      - main

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v1
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
      - name: Run tests
        run: sudo pytest
